# Configuracion de clases de entrega.
delivery.mx = co.fernandomulato.plugin.MexicoDeliveryPlugin
delivery.co = co.fernandomulato.plugin.ColombiaDeliveryPlugin
delivery.arg = co.fernandomulato.plugin.ArgentinaDeliveryPlugin
