@startuml Context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Sistema de Agendamiento de Citas Médicas - Nivel 1 (Contexto)

System(sistema, "Sistema de Agendamiento de Citas Médicas (Aplicación de Escritorio)", "Aplicación monolítica en capas (MVC) para gestión de citas e historias clínicas")

System_Ext(email, "Servicio de Correo Electrónico", "Servicio externo para envío de notificaciones")


Rel(sistema, email, "Envía notificaciones", "SMTP")

@enduml